
GET http://localhost:4000/todos


###
POST  http://localhost:4000/todos
Content-Type: application/json

{
    "title":"Code",
    "description":"Finished on APIS",
    "image":"https://cdn.pixabay.com/photo/2017/07/31/14/45/code-2558220_640.jpg"
}